# Project information
site_name: 盛世开源
site_url: http://static.asmatrix.com/site-asmatrix
site_author: Pastoral
site_description: >-
  软件产品展示, 涵盖教育、电力和物流。

dev_addr: 192.168.1.63:8100

# Repository, 支持github编辑链接
repo_name: 'GitHub: 产品文档'
repo_url: 'https://github.com/huhongjun/mkdocs-asmatrix'
# edit_uri: 'blob/master/docs'

# Copyright
copyright: Copyright &copy; 2016 - 2020 Hu Hongjun

nav:
  - Home: index.md
  - 教育软件:
    - 三维地球教学软件: education/earthview.md
    - 学历教育乐学通: education/lexuetong-xueli.md
    - 高职乐学通: education/lexuetong-gaozhi.md
    - 享学吧: education/xiangxueba.md
    - 网络教育学生服务平台: education/xueli-sns.md
    - 学习平台elcms: education/elcms.md
    - 教学资源管理平台: education/resu.md   
    - 学科知识服务平台: education/skp.md   
    - 后勤服务预约与申报系统: education/houqin-service.md   
    - 设备采购管理系统: education/shebeicaigou.md   
    - 教室资源管理系统: education/jiaoshiziyuan.md   
    - 实验室安全及在线考试系统: education/shiyanshi-test.md   
    - 技能型人才就业服务平台: education/dkjob.md   
    - 远程学历教育综合运营平台: education/xueliyunying.md   
    - 职业教育学习平台: education/zhiyejiaoyu-lms.md   

  - 电力软件:
    - 输电线路激光点云解决方案: power/lidar.md
    - 基于深度学习的点云分类系统: power/lidar-deeplearning.md
    - 输电线路巡检大数据分析系统: power/lidar-bigdata.md
    - 综合管廊智能巡检与综合监控: power/zhgl.md
    - 全景影像制作与展示解决方案: power/globe360.md
    - 直升机巡检数据存储管理系统: power/als-store.md
    - 航巡缺陷库管理系统: power/lidar-qxk.md
    - 输电线路差异化防雷性能及措施评估系统: power/thunder.md
    - 智能管控与航巡集成方案: power/lidar-integration.md

  - 物流软件:
    - 国家邮政包刷分拣处理系统: 'logistics/psmis.md'
    - 公路货运综合处理系统: 'logistics/cargomis.md'

  - 网站建设:
    - 企业网站: website/site-org.md
    - 教育网站: website/site-edu.md
    
  - 企业应用:
    - 协同办公平台: software/cop.md
    - 集团全面预决算管理: software/budget.md
    - 企业IT资产管理: software/itdb.md
    - 体育场馆在线预订平台: software/dsweb.md
    - 移动App: software/app.md
    
  - 课程课件:
    - 社会化学习课程: course/sociallearning.md
    - 发展力: course/fazhanli.md
    - 新生入学指南: course/xinshengruxue.md
    - 销售人员职业素养: course/cs-sales.md
    - 目标管理与时间管理: course/cs-objective.md
    - 干部管理素质与领导力测评: course/cs-sales.md
    - 干部能力提升-角色转变: course/cs-sales.md
    - 人保财险-销售系列课程: course/cs-sales.md
    - 人保财险 - 团队激励: course/cs-sales.md
    - 人保财险 - 有效增员: course/cs-sales.md
    - 学习型组织建设: course/cs-learningorg.md
    - 电子杂志北京航天信息培训学校: course/cs-sales.md
    - 国电安规游戏化课程: course/cs-sales.md
    - 嘉实基金新员工入职培训课程: course/cs-sales.md
    - 课件封装框架: course/cs-sales.md
    - 中医药文化教育特色资源库: course/cs-sales.md
    - HTML5教育小游戏: course/cs-sales.md
    - 游戏化测验: course/cs-sales.md
    
  - 开发服务:
    - 开源软件: opensource/opensource.md
    - 咨询培训: service/consulting.md
    - 定制开发: service/customdev.md
    - 在线演示: service/demo.md

  - 关于我们: 
    - 项目清单: about/projectlist.md
    - 我们是谁: about/about.md

# Configuration
theme:
  name: material
  logo: "img/favicon.ico"
  language: 'zh'
  palette:  
    primary: 'light blue' # 主色调,影响header,footer等的背景色
    accent: 'indigo'      # 点击链接相关颜色
  feature:
    tabs: true  # 横向导航  
  custom_dir: docs/resources/

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/huhongjun
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/huhongjun
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/huhongjun/

#扩展样式
extra_css:
  - resources/css/extra.css

# Extensions
markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true
