name: Publish docs to ghpages and S3
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env: 
      AWS_S3_BUCKET_NAME: static.asmatrix.com
      AWS_REGION: ap-northeast-1
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Deploy docs to GitHub Pages branch
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.16
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base