name: Publish ghpages to S3(manual)
on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'AWS_S3_BUCKET_NAME'
        required: true
        default: 'static.asmatrix.com'
      bucket_dir:
        description: 'AWS_REGION'
        required: true
        default: 'ap-northeast-1'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env: 
      AWS_S3_BUCKET_NAME: static.asmatrix.com
      AWS_REGION: ap-northeast-1
    steps:
      - name: Checkout ghpages
        uses: actions/checkout@v2
        with:
          ref: gh-pages        

      - name: Sync docs to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
          # SOURCE_DIR: ''  # optional: defaults to entire github repository
          DEST_DIR: 'site-asmatrix' #dir inside S3 bucket 

      - name: Workflow dispatcher
        run: |
          echo "Hello ${{ github.event.inputs.bucket_name }}!"
          echo "- in ${{ github.event.inputs.bucket_dir }}!"      
