name: upload ghpages to S3(manual)
on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'AWS S3 Bucket Name'
        required: true
        default: 'static.asmatrix.com'
      bucket_region:
        description: 'AWS Region(ap-eastnorth-1,us-east-1)'
        required: true
        default: 'ap-east-1'
      bucket_dir:
        description: 'Bucket Directory(eg. site-docu,defaults to the root of the bucket.)'
        required: false
        default: 'site-asmatrix'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env: 
      AWS_S3_BUCKET_NAME: static.asmatrix.com
      AWS_REGION: ap-east-1
    steps:
      - name: Checkout ghpages
        uses: actions/checkout@v2
        with:
          ref: gh-pages        

      - name: Debug info
        run: |
          echo "Bucket Name: ${{ github.event.inputs.bucket_name }}, Region: ${{ github.event.inputs.bucket_region }}"
          echo "Bucker Sync Dir: ${{ github.event.inputs.bucket_dir }}"
          echo "PWD: ${PWD}"
          ls -al

      - name: Sync docs to AWS S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: ${{ env.AWS_REGION }}
          # AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET_NAME }}
          # SOURCE_DIR: ''  # optional: defaults to entire github repository
          # DEST_DIR: 'site-asmatrix' #dir inside S3 bucket
          AWS_REGION: ${{ github.event.inputs.bucket_region }}
          AWS_S3_BUCKET: ${{ github.event.inputs.bucket_name }}
          DEST_DIR: ${{ github.event.inputs.bucket_dir }}
